In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set(style="darkgrid")
import statsmodels.formula.api as smf

In [26]:
a = pd.read_csv('test.csv')

In [28]:
for i in a.iloc[:,-1]:
    print(i)

Benign
Benign
malignant
Benign
Benign
malignant
malignant
Benign
Benign
Benign
Benign
Benign
malignant
Benign
Benign
malignant
Benign
Benign
Benign
Benign
Benign
Benign
malignant
Benign
Benign
Benign
Benign
malignant
malignant
malignant
malignant
malignant
Benign
Benign
malignant
Benign
Benign
Benign
malignant
Benign
malignant
Benign
malignant
Benign
Benign
Benign
Benign
Benign
Benign
Benign
malignant
malignant
malignant
malignant
malignant
malignant
Benign
malignant
Benign
Benign
Benign
Benign
Benign
malignant
Benign
Benign
Benign
Benign
Benign
malignant
malignant
malignant
malignant
malignant
Benign
malignant
Benign
Benign
Benign
Benign
Benign
Benign
malignant
malignant
Benign
Benign
Benign
malignant
malignant
Benign
Benign
malignant
Benign
Benign
Benign
Benign
malignant
Benign
Benign
Benign
Benign
Benign
Benign
malignant
Benign
malignant
malignant
malignant
Benign
Benign
Benign
Benign
Benign
malignant
malignant
Benign
Benign
Benign
Benign
malignant
malignant
malignant
malignant
mali

In [2]:
data = pd.read_csv('E:/PDFs/Class Room/cancer.csv')
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
id                         569 non-null int64
diagnosis                  569 non-null object
radius_mean                569 non-null float64
texture_mean               569 non-null float64
perimeter_mean             569 non-null float64
area_mean                  569 non-null float64
smoothness_mean            569 non-null float64
compactness_mean           569 non-null float64
concavity_mean             569 non-null float64
concave points_mean        569 non-null float64
symmetry_mean              569 non-null float64
fractal_dimension_mean     569 non-null float64
radius_se                  569 non-null float64
texture_se                 569 non-null float64
perimeter_se               569 non-null float64
area_se                    569 non-null float64
smoothness_se              569 non-null float64
compactness_se             569 non-null float64
concavity_se               569 non

In [4]:
data = data.drop(['id'],axis=1)

In [5]:
data['diagnosis'].replace(['M','B'],['malignant','Benign'],inplace=True)
data.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0  malignant        17.99         10.38          122.80     1001.0   
1  malignant        20.57         17.77          132.90     1326.0   
2  malignant        19.69         21.25          130.00     1203.0   
3  malignant        11.42         20.38           77.58      386.1   
4  malignant        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x = data.iloc[:,1:31]
y = data.iloc[:,0]

In [8]:
x.keys()

Index(['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean',
       'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

# Random Forest

In [10]:
# Bi=uild random forest classifier
from sklearn.ensemble import RandomForestClassifier
rmf = RandomForestClassifier(max_depth=3,random_state=0)
rf_class = rmf.fit(x_train,y_train)
rmf

RandomForestClassifier(max_depth=3, random_state=0)

In [11]:
# Predicting test anf train data
rf_y_test = rf_class.predict(x_test)

In [12]:
#build confusion matrix on test and train
from sklearn.metrics import confusion_matrix
rf_cm_test = confusion_matrix(y_test,rf_y_test)
rf_cm_test

array([[108,   3],
       [  4,  56]], dtype=int64)

In [13]:
rf_y_train = rf_class.predict(x_train)

In [14]:
rf_cm_train = confusion_matrix(y_train,rf_y_train)
rf_cm_train

array([[244,   2],
       [  7, 145]], dtype=int64)

In [21]:
y_test.to_csv('test.csv')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.


In [30]:
# Saving model to disk
import pickle
pickle.dump(rf_class, open('rf_model.pkl','wb'))

In [33]:
x_test.to_csv('E:/Flask/herokuapp/venv/x_test.csv')

In [45]:
# Loading model to compare the results
model = pickle.load(open('rf_model.pkl','rb'))
y_pred = model.predict(x_test)
y_pred

array(['Benign', 'Benign', 'Benign', 'malignant', 'Benign', 'Benign',
       'malignant', 'malignant', 'Benign', 'Benign', 'malignant',
       'Benign', 'Benign', 'malignant', 'Benign', 'Benign', 'malignant',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'malignant', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign',
       'malignant', 'malignant', 'malignant', 'malignant', 'Benign',
       'Benign', 'malignant', 'Benign', 'Benign', 'Benign', 'malignant',
       'Benign', 'malignant', 'Benign', 'malignant', 'Benign', 'Benign',
       'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'malignant',
       'malignant', 'Benign', 'malignant', 'malignant', 'malignant',
       'Benign', 'malignant', 'Benign', 'Benign', 'Benign', 'Benign',
       'Benign', 'malignant', 'malignant', 'Benign', 'Benign', 'Benign',
       'malignant', 'malignant', 'malignant', 'malignant', 'malignant',
       'malignant', 'Benign', 'malignant', 'Benign', 'Benign', 'Benign',
       'Beni

In [52]:
a = pd.read_csv('E:/Flask/herokuapp/venv/test.csv')


In [53]:
b = []
for i in a['Class']:
    print(i)
    b.append(i)

Benign
Benign
Benign
malignant
Benign
Benign
malignant
malignant
Benign
Benign
Benign
Benign
Benign
malignant
Benign
Benign
malignant
Benign
Benign
Benign
Benign
Benign
Benign
malignant
Benign
Benign
Benign
Benign
malignant
malignant
malignant
malignant
malignant
Benign
Benign
malignant
Benign
Benign
Benign
malignant
Benign
malignant
Benign
malignant
Benign
Benign
Benign
Benign
Benign
Benign
Benign
malignant
malignant
malignant
malignant
malignant
malignant
Benign
malignant
Benign
Benign
Benign
Benign
Benign
malignant
Benign
Benign
Benign
Benign
Benign
malignant
malignant
malignant
malignant
malignant
Benign
malignant
Benign
Benign
Benign
Benign
Benign
Benign
malignant
malignant
Benign
Benign
Benign
malignant
malignant
Benign
Benign
malignant
Benign
Benign
Benign
Benign
malignant
Benign
Benign
Benign
Benign
Benign
Benign
malignant
Benign
malignant
malignant
malignant
Benign
Benign
Benign
Benign
Benign
malignant
malignant
Benign
Benign
Benign
Benign
malignant
malignant
malignant
maligna

In [44]:
from sklearn.metrics import accuracy_score,precision_score
accuracy_score(a,y_pred)

ValueError: Found input variables with inconsistent numbers of samples: [1, 171]

In [15]:
from sklearn.metrics import accuracy_score,precision_score
rf_acc_test = accuracy_score(y_test,rf_y_test)
print('Tested Accuracy is :',rf_acc_test)
rf_prec_test = precision_score(y_test,rf_y_test,average='weighted')
print('Tested Precision Is:',rf_prec_test)

Tested Accuracy is : 0.9181286549707602
Tested Precision Is: 0.9187705236689082


In [16]:
rf_acc_train = accuracy_score(y_train,rf_y_train)
print('Trained Accuracy Is:',rf_acc_train)
rf_prec_train = precision_score(y_train,rf_y_train,average='weighted')
print('Trained Precision Is:',rf_prec_train)

Trained Accuracy Is: 0.9849246231155779
Trained Precision Is: 0.9849323642862199


In [17]:
from sklearn import model_selection
from sklearn.ensemble import AdaBoostClassifier

seed =7
#num_trees = 30 # no of brances : 30 is default
kfold = model_selection.KFold(n_splits=10,random_state=seed)

result = model_selection.cross_val_score(rf_class,x_train,y_train,cv=kfold)
print(result)
print(kfold)

[0.975      0.95       1.         0.95       0.925      0.95
 1.         1.         0.97435897 0.94871795]
KFold(n_splits=10, random_state=7, shuffle=False)


In [18]:
print(result.mean())

0.9673076923076923


# ADA BOOST

In [19]:
from sklearn.ensemble import AdaBoostClassifier
num_trees = 30
adamodel = AdaBoostClassifier(n_estimators=num_trees, random_state=seed)

In [20]:
ada = adamodel.fit(x_train,y_train)
ada

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=30, random_state=7)

In [21]:
y_pred = ada.predict(x_test)

In [22]:
ada_cm_test = confusion_matrix(y_test,y_pred)
ada_cm_test

array([[95,  8],
       [ 4, 64]], dtype=int64)

In [23]:
y_pred_train = ada.predict(x_train)

In [24]:
ada_cm_train = confusion_matrix(y_train,y_pred_train)
ada_cm_train

array([[254,   0],
       [  0, 144]], dtype=int64)

In [25]:
ada_test_acc = accuracy_score(y_test,y_pred)
print('Accuracy fro test : ',ada_test_acc)
ada_test_prec = precision_score(y_test,y_pred,average='weighted')
print('Precision for Test : ',ada_test_prec)

Accuracy fro test :  0.9298245614035088
Precision for Test :  0.931478527969756


In [26]:
ada_train_acc = accuracy_score(y_train,y_pred_train)
print('Accuracy fro train : ',ada_train_acc)
ada_train_prec = precision_score(y_train,y_pred_train,average='weighted')
print('Precision for Train : ',ada_train_prec)

Accuracy fro train :  1.0
Precision for Train :  1.0


In [27]:
from sklearn import model_selection
kfold = model_selection.KFold(n_splits=10, random_state=seed)
results = model_selection.cross_val_score(adamodel,x_train,y_train,cv=kfold)
print(results)

[0.975      0.875      1.         0.925      0.925      0.95
 0.95       1.         1.         0.97435897]


In [28]:
print(results.mean())

0.9574358974358976
